### ISSUE TITLE
ssh for volumio

### ISSUE THREAD

**Issue by bcdiaconu** [jbonjean/docker-public-images#10]
It would be nice to have ssh for volumio in order to use remote ssh development environment.

**Comment by SelfhostedPro** [comment]
> It is good to have ssh for connecting visual studio code through it and have a full development environment within volumio image. That will enhance debugging experience. Therefore it would be a easy setup, quasi fully working system with powerful debug on both frontend and backend and also on/with shell scripts. And also it would benefit when creating new plugins the same way.
> 
> Unfortunately I struggle allot with docker and that's why I requested it here.

Try finding a video on dockerfile basics. This is something that you can do fairly easily for a local copy without the developer needing to push it upon everyone. 

You’ll just need to add the few lines above, a configuration for ssh (/etc/sshd/sshd_config) and have a COPY line to put it in the right place.
